const lesson3 = {
  vocabularies: [
    { jp: "いま", romaji: "ima", eng: "now", viet: "bây giờ" },
    { jp: "ごぜん", romaji: "gozen", eng: "morning / AM", viet: "buổi sáng / trước trưa" },
    { jp: "ごご", romaji: "gogo", eng: "afternoon / PM", viet: "buổi chiều / sau trưa" },
    { jp: "ひる", romaji: "hiru", eng: "noon", viet: "trưa" },
    { jp: "ぎんこう", romaji: "ginkou", eng: "bank", viet: "ngân hàng" },
    { jp: "たいいくかん", romaji: "taiikukan", eng: "gymnasium", viet: "nhà thi đấu / phòng thể dục" },
    { jp: "としょかん", romaji: "toshokan", eng: "library", viet: "thư viện" },
    { jp: "びょういん", romaji: "byouin", eng: "hospital", viet: "bệnh viện" },
    { jp: "ゆうびんきょく", romaji: "yuubinkyoku", eng: "post office", viet: "bưu điện" },
    { jp: "じゅぎょう", romaji: "jugyou", eng: "class / lesson", viet: "tiết học / buổi học" },
    { jp: "テスト", romaji: "tesuto", eng: "test / exam", viet: "bài kiểm tra" },
    { jp: "やすみ", romaji: "yasumi", eng: "rest / holiday", viet: "nghỉ / ngày nghỉ" },
    { jp: "時間", romaji: "jikan", eng: "time", viet: "thời gian" },
    { jp: "一分", romaji: "ippun", eng: "1 minute", viet: "1 phút" },
    { jp: "二分", romaji: "nifun", eng: "2 minutes", viet: "2 phút" },
    { jp: "三分", romaji: "sanpun", eng: "3 minutes", viet: "3 phút" },
    { jp: "四分", romaji: "yonpun", eng: "4 minutes", viet: "4 phút" },
    { jp: "五分", romaji: "gofun", eng: "5 minutes", viet: "5 phút" },
    { jp: "六分", romaji: "roppun", eng: "6 minutes", viet: "6 phút" },
    { jp: "七分", romaji: "nanafun", eng: "7 minutes", viet: "7 phút" },
    { jp: "八分", romaji: "happun", eng: "8 minutes", viet: "8 phút" },
    { jp: "九分", romaji: "kyuufun", eng: "9 minutes", viet: "9 phút" },
    { jp: "十分", romaji: "juppun", eng: "10 minutes", viet: "10 phút" },
    { jp: "十五分", romaji: "juugofun", eng: "15 minutes", viet: "15 phút" },
    { jp: "二十分", romaji: "nijuppun", eng: "20 minutes", viet: "20 phút" },
    { jp: "三十分", romaji: "sanjuppun", eng: "30 minutes", viet: "30 phút" },
    { jp: "何分", romaji: "nanpun", eng: "how many minutes", viet: "mấy phút" },
    { jp: "～時半", romaji: "~jihan", eng: "half past ~", viet: "~ giờ rưỡi" },
    { jp: "～曜日", romaji: "~youbi", eng: "day of the week ~", viet: "thứ ~" },
    { jp: "月曜日", romaji: "getsuyoubi", eng: "Monday", viet: "thứ Hai" },
    { jp: "火曜日", romaji: "kayoubi", eng: "Tuesday", viet: "thứ Ba" },
    { jp: "水曜日", romaji: "suiyoubi", eng: "Wednesday", viet: "thứ Tư" },
    { jp: "木曜日", romaji: "mokuyoubi", eng: "Thursday", viet: "thứ Năm" },
    { jp: "金曜日", romaji: "kinyoubi", eng: "Friday", viet: "thứ Sáu" },
    { jp: "土曜日", romaji: "doyoubi", eng: "Saturday", viet: "thứ Bảy" },
    { jp: "日曜日", romaji: "nichiyoubi", eng: "Sunday", viet: "Chủ nhật" },
    { jp: "何曜日", romaji: "nanyoubi", eng: "what day", viet: "thứ mấy" },
    { jp: "スケジュール", romaji: "sukejuuru", eng: "schedule / plan", viet: "lịch trình" },
    { jp: "アルバイト", romaji: "arubaito", eng: "part-time job", viet: "làm thêm / part-time" },
    { jp: "スキー", romaji: "sukii", eng: "skiing", viet: "trượt tuyết" },
    { jp: "パーティー", romaji: "paatii", eng: "party", viet: "bữa tiệc" },
    { jp: "バーベキュー", romaji: "baabekyuu", eng: "barbecue", viet: "nướng ngoài trời" },
    { jp: "はな火", romaji: "hanabi", eng: "fireworks", viet: "pháo hoa" },
    { jp: "(お)はなみ", romaji: "ohanami", eng: "cherry blossom viewing", viet: "ngắm hoa anh đào" },
    { jp: "ホームステイ", romaji: "hoomusutei", eng: "homestay", viet: "ở nhà dân" },
    { jp: "(お)まつり", romaji: "omatsuri", eng: "festival", viet: "lễ hội" },
    { jp: "うみ", romaji: "umi", eng: "sea / beach", viet: "biển" },
    { jp: "こうえん", romaji: "kouen", eng: "park", viet: "công viên" },
    { jp: "さくら", romaji: "sakura", eng: "cherry blossom", viet: "hoa anh đào" },
    { jp: "(お)さけ", romaji: "osake", eng: "Japanese rice wine (sake)", viet: "rượu sake" },
    { jp: "(お)すし", romaji: "osushi", eng: "sushi", viet: "sushi" },
    { jp: "バス", romaji: "basu", eng: "bus", viet: "xe buýt" },
    { jp: "(お)べんとう", romaji: "obentou", eng: "boxed lunch", viet: "cơm hộp" },
    { jp: "１年", romaji: "ichinen", eng: "one year", viet: "một năm" },
    { jp: "はる", romaji: "haru", eng: "spring", viet: "mùa xuân" },
    { jp: "なつ", romaji: "natsu", eng: "summer", viet: "mùa hè" },
    { jp: "あき", romaji: "aki", eng: "autumn", viet: "mùa thu" },
    { jp: "ふゆ", romaji: "fuyu", eng: "winter", viet: "mùa đông" },
    { jp: "ゴールデンウィーク", romaji: "goorudenwiiku", eng: "Golden Week", viet: "Tuần lễ Vàng" },
    { jp: "何", romaji: "nani", eng: "what", viet: "cái gì" },
    { jp: "いきます", romaji: "ikimasu", eng: "to go", viet: "đi" },
    { jp: "かえります", romaji: "kaerimasu", eng: "to return / go home", viet: "về" },
    { jp: "のみます", romaji: "nomimasu", eng: "to drink", viet: "uống" },
    { jp: "たべます", romaji: "tabemasu", eng: "to eat", viet: "ăn" },
    { jp: "みます", romaji: "mimasu", eng: "to see / to watch", viet: "xem" },
    { jp: "します", romaji: "shimasu", eng: "to do / to play / to hold", viet: "làm / chơi" },
    { jp: "スキーをします", romaji: "sukii o shimasu", eng: "to ski", viet: "trượt tuyết" },
    { jp: "いいですね", romaji: "ii desu ne", eng: "that sounds good / nice!", viet: "tuyệt đấy / hay đấy" },
    { jp: "えっ", romaji: "e", eng: "eh? / huh?", viet: "ơ? / hả?" },
    { jp: "へえ", romaji: "hee", eng: "wow / really", viet: "ồ / thật à" },
    { jp: "あさ", romaji: "asa", eng: "morning", viet: "buổi sáng" },
    { jp: "よる", romaji: "yoru", eng: "evening / night", viet: "buổi tối" },
    { jp: "まいにち", romaji: "mainichi", eng: "every day", viet: "hằng ngày" },
    { jp: "まいあさ", romaji: "maiasa", eng: "every morning", viet: "mỗi sáng" },
    { jp: "まいばん", romaji: "maiban", eng: "every evening", viet: "mỗi tối" },
    { jp: "あさごはん", romaji: "asagohan", eng: "breakfast", viet: "bữa sáng" },
    { jp: "ひるごはん", romaji: "hirugohan", eng: "lunch", viet: "bữa trưa" },
    { jp: "うち", romaji: "uchi", eng: "home, house", viet: "nhà" },
    { jp: "かいしゃ", romaji: "kaisha", eng: "company", viet: "công ty" },
    { jp: "学校", romaji: "gakkou", eng: "school", viet: "trường học" },
    { jp: "コンビニ", romaji: "konbini", eng: "convenience store", viet: "cửa hàng tiện lợi" },
    { jp: "ぎゅうにゅう", romaji: "gyuunyuu", eng: "milk", viet: "sữa bò" },
    { jp: "くだもの", romaji: "kudamono", eng: "fruit", viet: "hoa quả" },
    { jp: "サラダ", romaji: "sarada", eng: "salad", viet: "salad" },
    { jp: "チーズ", romaji: "chiizu", eng: "cheese", viet: "phô mai" },
    { jp: "インターネット", romaji: "intaanetto", eng: "internet", viet: "internet" },
    { jp: "しんぶん", romaji: "shinbun", eng: "newspaper", viet: "báo chí" },
    { jp: "テレビ", romaji: "terebi", eng: "television", viet: "ti vi" },
    { jp: "シーディー、ディーブイディー", romaji: "shiidii, diibuidii", eng: "CD, DVD", viet: "CD, DVD" },
    { jp: "何も", romaji: "nanimo", eng: "anything", viet: "cái gì cũng" },
    { jp: "どこ（へ）も", romaji: "doko(e)mo", eng: "anywhere", viet: "nơi nào cũng" },
    { jp: "かいます", romaji: "kaimasu", eng: "buy", viet: "mua" },
    { jp: "ききます", romaji: "kikimasu", eng: "listen", viet: "nghe" },
    { jp: "はたらきます", romaji: "hatarakimasu", eng: "work", viet: "làm việc" },
    { jp: "よみます", romaji: "yomimasu", eng: "read", viet: "đọc" },
    { jp: "ねます", romaji: "nemasu", eng: "sleep", viet: "ngủ" },
    { jp: "べんきょうします", romaji: "benkyoushimasu", eng: "study", viet: "học" },
    { jp: "きます", romaji: "kimasu", eng: "come, arrive", viet: "đến" }
  ],

  kanji: [
    { jp: "月",   hira: "つき",     romaji: "tsuki / getsu",      eng: "moon / month",                     viet: "mặt trăng / tháng" },
    { jp: "火",   hira: "ひ",       romaji: "hi / ka",            eng: "fire",                             viet: "lửa" },
    { jp: "水",   hira: "みず",     romaji: "mizu / sui",         eng: "water",                            viet: "nước" },
    { jp: "木",   hira: "き",       romaji: "ki / moku",          eng: "tree / wood",                      viet: "cây / gỗ" },
    { jp: "金",   hira: "かね",     romaji: "kane / kin",         eng: "gold / money",                     viet: "vàng / tiền" },
    { jp: "土",   hira: "つち",     romaji: "tsuchi / do",        eng: "earth / soil",                     viet: "đất" },
    { jp: "曜",   hira: "よう",     romaji: "yō",                 eng: "day (of the week)",                viet: "ngày trong tuần" },
    { jp: "何",   hira: "なに",     romaji: "nani / ka",          eng: "what",                             viet: "cái gì / nào" },
    { jp: "年",   hira: "とし",     romaji: "toshi / nen",        eng: "year",                             viet: "năm" },
    { jp: "時",   hira: "とき",     romaji: "toki / ji",          eng: "time / hour",                      viet: "thời gian / giờ" },
    { jp: "間",   hira: "あいだ",   romaji: "aida / kan",         eng: "interval / between",               viet: "khoảng / giữa" },
    { jp: "分",   hira: "ふん",     romaji: "fun / bun / wakeru", eng: "minute / divide / understand",     viet: "phút / hiểu" },

    // Từ ghép bổ sung để học sâu hơn
    { jp: "月曜日", hira: "げつようび", romaji: "getsuyoubi",     eng: "Monday",               viet: "thứ Hai" },
    { jp: "火曜日", hira: "かようび",   romaji: "kayoubi",         eng: "Tuesday",              viet: "thứ Ba" },
    { jp: "水曜日", hira: "すいようび", romaji: "suiyoubi",        eng: "Wednesday",            viet: "thứ Tư" },
    { jp: "木曜日", hira: "もくようび", romaji: "mokuyoubi",       eng: "Thursday",             viet: "thứ Năm" },
    { jp: "金曜日", hira: "きんようび", romaji: "kinyoubi",        eng: "Friday",               viet: "thứ Sáu" },
    { jp: "土曜日", hira: "どようび",   romaji: "doyoubi",         eng: "Saturday",             viet: "thứ Bảy" },
    { jp: "日曜日", hira: "にちようび", romaji: "nichiyoubi",      eng: "Sunday",               viet: "Chủ nhật" },
    { jp: "何曜日", hira: "なんようび", romaji: "nanyoubi",        eng: "what day of the week", viet: "thứ mấy" },
    { jp: "何時",   hira: "なんじ",     romaji: "nanji",           eng: "what time",            viet: "mấy giờ" },
    { jp: "何月",   hira: "なんがつ",   romaji: "nangatsu",        eng: "what month",           viet: "tháng mấy" },
    { jp: "何年",   hira: "なんねん",   romaji: "nannen",          eng: "what year",            viet: "năm nào" },
    { jp: "一年",   hira: "いちねん",   romaji: "ichinen",         eng: "one year",             viet: "một năm" },
    { jp: "四年",   hira: "よねん",     romaji: "yonen",           eng: "four years",           viet: "bốn năm" },
    { jp: "四年生", hira: "よねんせい", romaji: "yonensei",       eng: "4th year student",     viet: "học sinh năm tư" },
    { jp: "生年月日", hira: "せいねんがっぴ", romaji: "seinengappi", eng: "date of birth",    viet: "ngày tháng năm sinh" },
    { jp: "一時",   hira: "いちじ",     romaji: "ichiji",          eng: "1 o'clock",            viet: "1 giờ" },
    { jp: "一時間", hira: "いちじかん", romaji: "ichijikan",      eng: "1 hour",               viet: "1 tiếng" },
    { jp: "四月",   hira: "しがつ, よがつ", romaji: "shigatsu / yogatsu", eng: "April",       viet: "tháng Tư" },
    { jp: "七月",   hira: "しちがつ",   romaji: "shichigatsu",     eng: "July",                 viet: "tháng Bảy" },
    { jp: "九月",   hira: "くがつ",     romaji: "kugatsu",         eng: "September",            viet: "tháng Chín" },
    { jp: "お金",   hira: "おかね",     romaji: "okane",           eng: "money",                viet: "tiền" },
    { jp: "人間",   hira: "にんげん",   romaji: "ningen",          eng: "human / person",       viet: "con người" },
    { jp: "日",     hira: "ひ",         romaji: "hi / nichi",      eng: "day / sun / Japan",    viet: "ngày / mặt trời / Nhật" }
  ],

  grammar: [
    { jp: "Vます／Vません", romaji: "V masu / V masen", eng: "Will do / Will not do", viet: "sẽ làm / sẽ không làm" },
    { jp: "N（場所）へいきます／きます／かえります", romaji: "N (basho) e ikimasu / kimasu / kaerimasu", eng: "Go / come / return to a place N", viet: "đi / đến / về nơi N" },
    { jp: "N（を）Vます", romaji: "N (o) V masu", eng: "Perform an action V on object N", viet: "làm hành động V với đối tượng N" },
    { jp: "N（時間）にVます", romaji: "N (jikan) ni V masu", eng: "Do V at time N", viet: "làm V vào thời điểm N" },
    { jp: "N（場所）でVます", romaji: "N (basho) de V masu", eng: "Do V at/in place N", viet: "làm V tại nơi N" },
    { jp: "N（時間／曜日）からN（時間／曜日）まで", romaji: "N (jikan / youbi) kara N (jikan / youbi) made", eng: "From N (time/day) to N (time/day)", viet: "từ N đến N" },
    { jp: "N1やN2など", romaji: "N1 ya N2 nado", eng: "N1, N2, etc.", viet: "N1, N2, v.v." },
    { jp: "何もしません／どこ（へ）もいきません", romaji: "nani mo shimasen / doko (e) mo ikimasen", eng: "Do nothing / Go nowhere", viet: "không làm gì cả / không đi đâu cả" }
  ]
};