const lesson1 = {
  vocabularies: [
    { jp: "私", romaji: "watashi", eng: "I", viet: "tôi" },
    { jp: "なまえ", romaji: "namae", eng: "name", viet: "tên" },
    { jp: "くに", romaji: "kuni", eng: "country", viet: "quốc gia" },
    { jp: "日本", romaji: "nihon", eng: "Japan", viet: "Nhật Bản" },
    { jp: "かんこく", romaji: "kankoku", eng: "Korea", viet: "Hàn Quốc" },
    { jp: "ちゅうごく", romaji: "chuugoku", eng: "China", viet: "Trung Quốc" },
    { jp: "アメリカ", romaji: "amerika", eng: "America", viet: "Mỹ" },
    { jp: "イタリア", romaji: "itaria", eng: "Italy", viet: "Ý" },
    { jp: "オーストラリア", romaji: "oosutoraria", eng: "Australia", viet: "Úc" },
    { jp: "ロシア", romaji: "roshia", eng: "Russia", viet: "Nga" },
    { jp: "タイ", romaji: "tai", eng: "Thailand", viet: "Thái Lan" },
    { jp: "高校", romaji: "koukou", eng: "high school", viet: "trường cấp 3" },
    { jp: "大学", romaji: "daigaku", eng: "university", viet: "đại học" },
    { jp: "日本語学校", romaji: "nihongo gakkou", eng: "Japanese language school", viet: "trường tiếng Nhật" },
    { jp: "しごと", romaji: "shigoto", eng: "job", viet: "công việc" },
    { jp: "学生", romaji: "gakusei", eng: "student", viet: "học sinh / sinh viên" },
    { jp: "先生", romaji: "sensei", eng: "instructor", viet: "giáo viên / thầy cô" },
    { jp: "きょうし", romaji: "kyoushi", eng: "teacher", viet: "giáo viên" },
    { jp: "かいしゃいん", romaji: "kaishain", eng: "company employee", viet: "nhân viên công ty" },
    { jp: "〜しゃいん", romaji: "~shain", eng: "employee of ~ company", viet: "nhân viên của công ty ~" },
    { jp: "〜さん", romaji: "~san", eng: "Mr. / Ms. / Mrs.", viet: "ông / bà / cô / anh / chị" },
    { jp: "〜人", romaji: "~jin", eng: "person / nationality", viet: "người / quốc tịch" },
    { jp: "どちら", romaji: "dochira", eng: "where / which way", viet: "đâu / hướng nào" },
    { jp: "はじめまして", romaji: "hajimemashite", eng: "Nice to meet you (first time)", viet: "rất vui được gặp bạn (lần đầu)" },
    { jp: "よろしくおねがいします", romaji: "yoroshiku onegaishimasu", eng: "Please take care of me / I look forward to working with you", viet: "rất mong được giúp đỡ / mong được hợp tác" },
    { jp: "こちらこそ", romaji: "kochirakoso", eng: "Likewise / same here", viet: "tôi cũng vậy" },
    { jp: "あのう", romaji: "anou", eng: "um... / excuse me...", viet: "ừm... / xin lỗi..." },
    { jp: "すみません", romaji: "sumimasen", eng: "excuse me / I'm sorry", viet: "xin lỗi / cho hỏi" },
    { jp: "そうですか", romaji: "sou desu ka", eng: "Is that so? / I see", viet: "vậy à? / tôi hiểu rồi" },
    { jp: "誕生日", romaji: "tanjoubi", eng: "birthday", viet: "sinh nhật" },
    { jp: "ブラジル", romaji: "burajiru", eng: "Brazil", viet: "Brazil" },
    { jp: "いつ", romaji: "itsu", eng: "when", viet: "khi nào" },
    { jp: "一月", romaji: "ichigatsu", eng: "January", viet: "tháng Một" },
    { jp: "二月", romaji: "nigatsu", eng: "February", viet: "tháng Hai" },
    { jp: "三月", romaji: "sangatsu", eng: "March", viet: "tháng Ba" },
    { jp: "四月", romaji: "shigatsu", eng: "April", viet: "tháng Tư" },
    { jp: "五月", romaji: "gogatsu", eng: "May", viet: "tháng Năm" },
    { jp: "六月", romaji: "rokugatsu", eng: "June", viet: "tháng Sáu" },
    { jp: "七月", romaji: "shichigatsu", eng: "July", viet: "tháng Bảy" },
    { jp: "八月", romaji: "hachigatsu", eng: "August", viet: "tháng Tám" },
    { jp: "九月", romaji: "kugatsu", eng: "September", viet: "tháng Chín" },
    { jp: "十月", romaji: "juugatsu", eng: "October", viet: "tháng Mười" },
    { jp: "十一月", romaji: "juuichigatsu", eng: "November", viet: "tháng Mười Một" },
    { jp: "十二月", romaji: "juunigatsu", eng: "December", viet: "tháng Mười Hai" },
    { jp: "一日", romaji: "tsuitachi", eng: "1st day", viet: "ngày 1" },
    { jp: "二日", romaji: "futsuka", eng: "2nd day", viet: "ngày 2" },
    { jp: "三日", romaji: "mikka", eng: "3rd day", viet: "ngày 3" },
    { jp: "四日", romaji: "yokka", eng: "4th day", viet: "ngày 4" },
    { jp: "五日", romaji: "itsuka", eng: "5th day", viet: "ngày 5" },
    { jp: "六日", romaji: "muika", eng: "6th day", viet: "ngày 6" },
    { jp: "七日", romaji: "nanoka", eng: "7th day", viet: "ngày 7" },
    { jp: "八日", romaji: "youka", eng: "8th day", viet: "ngày 8" },
    { jp: "九日", romaji: "kokonoka", eng: "9th day", viet: "ngày 9" },
    { jp: "十日", romaji: "tooka", eng: "10th day", viet: "ngày 10" },
    { jp: "十一日", romaji: "juuichinichi", eng: "11th day", viet: "ngày 11" },
    { jp: "十二日", romaji: "juuninichi", eng: "12th day", viet: "ngày 12" },
    { jp: "十三日", romaji: "juusannichi", eng: "13th day", viet: "ngày 13" },
    { jp: "十四日", romaji: "juuyokka", eng: "14th day", viet: "ngày 14" },
    { jp: "十五日", romaji: "juugonichi", eng: "15th day", viet: "ngày 15" },
    { jp: "十六日", romaji: "juurokunichi", eng: "16th day", viet: "ngày 16" },
    { jp: "十七日", romaji: "juushichinichi", eng: "17th day", viet: "ngày 17" },
    { jp: "十八日", romaji: "juuhachinichi", eng: "18th day", viet: "ngày 18" },
    { jp: "十九日", romaji: "juukunichi", eng: "19th day", viet: "ngày 19" },
    { jp: "二十日", romaji: "hatsuka", eng: "20th day", viet: "ngày 20" },
    { jp: "二十一日", romaji: "nijuuichinichi", eng: "21st day", viet: "ngày 21" },
    { jp: "二十二日", romaji: "nijuuninichi", eng: "22nd day", viet: "ngày 22" },
    { jp: "二十三日", romaji: "nijuusannichi", eng: "23rd day", viet: "ngày 23" },
    { jp: "二十四日", romaji: "nijuuyokka", eng: "24th day", viet: "ngày 24" },
    { jp: "二十五日", romaji: "nijuugonichi", eng: "25th day", viet: "ngày 25" },
    { jp: "二十六日", romaji: "nijuurokunichi", eng: "26th day", viet: "ngày 26" },
    { jp: "二十七日", romaji: "nijuushichinichi", eng: "27th day", viet: "ngày 27" },
    { jp: "二十八日", romaji: "nijuuhachinichi", eng: "28th day", viet: "ngày 28" },
    { jp: "二十九日", romaji: "nijuukunichi", eng: "29th day", viet: "ngày 29" },
    { jp: "三十日", romaji: "sanjuunichi", eng: "30th day", viet: "ngày 30" },
    { jp: "三十一日", romaji: "sanjuuichinichi", eng: "31st day", viet: "ngày 31" },
    { jp: "一才", romaji: "issai", eng: "1 year old", viet: "1 tuổi" },
    { jp: "二才", romaji: "nisai", eng: "2 years old", viet: "2 tuổi" },
    { jp: "三才", romaji: "sansai", eng: "3 years old", viet: "3 tuổi" },
    { jp: "四才", romaji: "yonsai", eng: "4 years old", viet: "4 tuổi" },
    { jp: "五才", romaji: "gosai", eng: "5 years old", viet: "5 tuổi" },
    { jp: "六才", romaji: "rokusai", eng: "6 years old", viet: "6 tuổi" },
    { jp: "七才", romaji: "nanasai", eng: "7 years old", viet: "7 tuổi" },
    { jp: "八才", romaji: "hassai", eng: "8 years old", viet: "8 tuổi" },
    { jp: "九才", romaji: "kyuusai", eng: "9 years old", viet: "9 tuổi" },
    { jp: "十才", romaji: "jussai", eng: "10 years old", viet: "10 tuổi" },
    { jp: "十一才", romaji: "juuissai", eng: "11 years old", viet: "11 tuổi" },
    { jp: "十八才", romaji: "juuhassai", eng: "18 years old", viet: "18 tuổi" },
    { jp: "二十才", romaji: "hatachi", eng: "20 years old", viet: "20 tuổi" },
    { jp: "三十才", romaji: "sanjuussai", eng: "30 years old", viet: "30 tuổi" },
    { jp: "何才", romaji: "nansai", eng: "how old", viet: "bao nhiêu tuổi" },
    { jp: "しゅみ", romaji: "shumi", eng: "hobby", viet: "sở thích" },
    { jp: "スポーツ", romaji: "supōtsu", eng: "sports", viet: "thể thao" },
    { jp: "サッカー", romaji: "sakkā", eng: "soccer", viet: "bóng đá" },
    { jp: "テニス", romaji: "tenisu", eng: "tennis", viet: "tennis" },
    { jp: "すいえい", romaji: "suiei", eng: "swimming", viet: "bơi lội" },
    { jp: "えいが", romaji: "eiga", eng: "movie", viet: "phim" },
    { jp: "おんがく", romaji: "ongaku", eng: "music", viet: "âm nhạc" },
    { jp: "どくしょ", romaji: "dokusho", eng: "reading", viet: "đọc sách" },
    { jp: "りょこう", romaji: "ryokō", eng: "travel", viet: "du lịch" },
    { jp: "りょうり", romaji: "ryōri", eng: "cooking / food", viet: "nấu ăn / món ăn" },
    { jp: "何", romaji: "nani", eng: "what", viet: "cái gì" },
    { jp: "あ（っ）", romaji: "a (tsu)", eng: "ah! / oh!", viet: "à! / ôi!" },
    { jp: "わあ", romaji: "waa", eng: "wow", viet: "wow / tuyệt vời" },
    { jp: "おなじですね", romaji: "onaji desu ne", eng: "same, isn’t it?", viet: "giống nhau nhỉ?" }
  ],
    kanji: [
    { jp: "私",   hira: "わたし",   romaji: "watashi",         eng: "I / me",                        viet: "tôi / bản thân / mình" },
    { jp: "人",   hira: "ひと",     romaji: "hito / jin / nin", eng: "person / people",              viet: "người / con người" },
    { jp: "日本人", hira: "にほんじん", romaji: "nihonjin",     eng: "Japanese person",              viet: "người Nhật" },
    { jp: "才",   hira: "さい",     romaji: "sai",             eng: "years old (counter) / talent", viet: "tuổi (đếm tuổi) / tài năng" },
    { jp: "学生", hira: "がくせい", romaji: "gakusei",         eng: "student",                      viet: "học sinh / sinh viên" },
    { jp: "学校", hira: "がっこう", romaji: "gakkou",          eng: "school",                       viet: "trường học" },
    { jp: "大学", hira: "だいがく", romaji: "daigaku",         eng: "university",                   viet: "đại học" },
    { jp: "先生", hira: "せんせい", romaji: "sensei",          eng: "teacher / master / doctor",    viet: "giáo viên / thầy cô / bác sĩ" },
    { jp: "日",   hira: "ひ・にち", romaji: "hi / nichi / jitsu", eng: "day / sun / Japan",          viet: "ngày / mặt trời / Nhật Bản" },
    { jp: "日本", hira: "にほん・にっぽん", romaji: "nihon / nippon", eng: "Japan",                 viet: "Nhật Bản" },
    { jp: "誕生日", hira: "たんじょうび", romaji: "tanjoubi",   eng: "birthday",                     viet: "sinh nhật" },
    { jp: "本",   hira: "ほん・もと", romaji: "hon / moto",    eng: "book / origin / main / Japan", viet: "sách / gốc / bản / Nhật Bản" },
    { jp: "語",   hira: "ご・かたる", romaji: "go / kataru",   eng: "language / word / to speak",   viet: "ngôn ngữ / lời / nói" },
    { jp: "日本語", hira: "にほんご", romaji: "nihongo",       eng: "Japanese language",            viet: "tiếng Nhật" },

    // Các ngày trong tháng (1~10, 20)
    { jp: "一日", hira: "ついたち", romaji: "tsuitachi",       eng: "1st day of the month",         viet: "ngày mùng 1" },
    { jp: "二日", hira: "ふつか",   romaji: "futsuka",         eng: "2nd day / two days",           viet: "ngày mùng 2 / 2 ngày" },
    { jp: "三日", hira: "みっか",   romaji: "mikka",           eng: "3rd day / three days",         viet: "ngày mùng 3 / 3 ngày" },
    { jp: "四日", hira: "よっか",   romaji: "yokka",           eng: "4th day / four days",          viet: "ngày mùng 4 / 4 ngày" },
    { jp: "五日", hira: "いつか",   romaji: "itsuka",          eng: "5th day / five days",          viet: "ngày mùng 5 / 5 ngày" },
    { jp: "六日", hira: "むいか",   romaji: "muika",           eng: "6th day / six days",           viet: "ngày mùng 6 / 6 ngày" },
    { jp: "七日", hira: "なのか",   romaji: "nanoka",          eng: "7th day / seven days",         viet: "ngày mùng 7 / 7 ngày" },
    { jp: "八日", hira: "ようか",   romaji: "youka",           eng: "8th day / eight days",         viet: "ngày mùng 8 / 8 ngày" },
    { jp: "九日", hira: "ここのか", romaji: "kokonoka",       eng: "9th day / nine days",          viet: "ngày mùng 9 / 9 ngày" },
    { jp: "十日", hira: "とおか",   romaji: "tooka",           eng: "10th day / ten days",          viet: "ngày mùng 10 / 10 ngày" },
    { jp: "二十日", hira: "はつか", romaji: "hatsuka",        eng: "20th day / twenty days",       viet: "ngày 20 / 20 ngày" },

    // Số tuổi
    { jp: "一才", hira: "いっさい", romaji: "issai",           eng: "1 year old",                   viet: "1 tuổi" },
    { jp: "八才", hira: "はっさい", romaji: "hassai",          eng: "8 years old",                  viet: "8 tuổi" },
    { jp: "十才", hira: "じゅっさい", romaji: "jussai",       eng: "10 years old",                 viet: "10 tuổi" }
    ],
  grammar: [
    { 
        jp: "N1はN2です", 
        romaji: "N1 wa N2 desu", 
        eng: "N1 is N2", 
        viet: "N1 là N2"
    },
    { 
        jp: "N1は〜のN2です", 
        romaji: "N1 wa ~ no N2 desu", 
        eng: "N1 is the N2 of ~", 
        viet: "N1 là N2 của ~"
    },
    { 
        jp: "N1のN2です", 
        romaji: "N1 no N2 desu", 
        eng: "N2 of N1 / N2 belonging to N1", 
        viet: "N2 của N1 / N2 thuộc về N1"
    },
    { 
        jp: "N1もN2です", 
        romaji: "N1 mo N2 desu", 
        eng: "N1 is also N2", 
        viet: "N1 cũng là N2"
    },
    { 
        jp: "N1はN2じゃありません（ではありません）", 
        romaji: "N1 wa N2 ja arimasen (dewa arimasen)", 
        eng: "N1 is not N2", 
        viet: "N1 không phải là N2"
    },
    { 
        jp: "N1とN2", 
        romaji: "N1 to N2", 
        eng: "N1 and N2", 
        viet: "N1 và N2"
    },
    { 
        jp: "Nはどこですか", 
        romaji: "N wa doko desu ka", 
        eng: "Where is N?", 
        viet: "N ở đâu?"
    },
    { 
        jp: "Nは？", 
        romaji: "N wa?", 
        eng: "How about N? / And N?", 
        viet: "Còn N thì sao? / Và N?"
    },
    { 
        jp: "N1はN2ですか", 
        romaji: "N1 wa N2 desu ka", 
        eng: "Is N1 N2?", 
        viet: "N1 có phải là N2 không?"
    }
  ]
};