const lesson2 = {
  vocabularies: [
    { jp: "ここ", romaji: "koko", eng: "here", viet: "đây / chỗ này" },
    { jp: "こちら", romaji: "kochira", eng: "this way", viet: "bên này / hướng này (lịch sự)" },
    { jp: "そこ", romaji: "soko", eng: "there", viet: "đó / chỗ đó (gần người nghe)" },
    { jp: "そちら", romaji: "sochira", eng: "that way", viet: "bên đó (lịch sự)" },
    { jp: "あそこ", romaji: "asoko", eng: "over there", viet: "kia / chỗ kia (xa cả hai)" },
    { jp: "あちら", romaji: "achira", eng: "that way over there", viet: "bên kia (lịch sự)" },
    { jp: "インフォメーション", romaji: "infomēshon", eng: "information desk", viet: "quầy thông tin" },
    { jp: "ＡＴＭ", romaji: "ATM", eng: "ATM", viet: "máy rút tiền tự động" },
    { jp: "エスカレーター", romaji: "esukarētā", eng: "escalator", viet: "thang cuốn" },
    { jp: "エレベーター", romaji: "erebētā", eng: "elevator", viet: "thang máy" },
    { jp: "きつえんじょ", romaji: "kitsuenjo", eng: "smoking area", viet: "khu vực hút thuốc" },
    { jp: "トイレ", romaji: "toire", eng: "toilet", viet: "nhà vệ sinh" },
    { jp: "レジ", romaji: "reji", eng: "cash register", viet: "quầy thu ngân" },
    { jp: "きっさてん", romaji: "kissaten", eng: "coffee shop", viet: "quán cà phê truyền thống" },
    { jp: "スーパー", romaji: "sūpā", eng: "supermarket", viet: "siêu thị" },
    { jp: "１００円ショップ", romaji: "hyaku en shoppu", eng: "100 yen shop", viet: "cửa hàng 100 yên (Daiso, Seria…)" },
    { jp: "レストラン", romaji: "resutoran", eng: "restaurant", viet: "nhà hàng" },
    { jp: "ちか", romaji: "chika", eng: "basement", viet: "tầng hầm" },
    { jp: "カメラ", romaji: "kamera", eng: "camera", viet: "máy ảnh" },
    { jp: "けいたいでんわ", romaji: "keitai denwa", eng: "mobile phone", viet: "điện thoại di động" },
    { jp: "でんじしょ", romaji: "denshijo", eng: "electronic dictionary", viet: "từ điển điện tử" },
    { jp: "パソコン", romaji: "pasokon", eng: "personal computer", viet: "máy tính cá nhân" },
    { jp: "くつ", romaji: "kutsu", eng: "shoes", viet: "giày" },
    { jp: "けしゴム", romaji: "keshigomu", eng: "eraser", viet: "cục tẩy" },
    { jp: "ペン", romaji: "pen", eng: "pen", viet: "bút mực / bút bi" },
    { jp: "トイレットペーパー", romaji: "toiretto pēpā", eng: "toilet paper", viet: "giấy vệ sinh" },
    { jp: "あぶら", romaji: "abura", eng: "oil", viet: "dầu / mỡ" },
    { jp: "ケーキ", romaji: "kēki", eng: "cake", viet: "bánh ngọt / bánh ga tô" },
    { jp: "こめ", romaji: "kome", eng: "rice", viet: "gạo" },
    { jp: "たまご", romaji: "tamago", eng: "egg", viet: "trứng" },
    { jp: "パン", romaji: "pan", eng: "bread", viet: "bánh mì" },
    { jp: "てんいん", romaji: "ten'in", eng: "salesperson", viet: "nhân viên bán hàng" },
    { jp: "～かい", romaji: "~kai", eng: "~ floor", viet: "tầng ~" },
    { jp: "いっかい", romaji: "ikkai", eng: "first floor", viet: "tầng 1" },
    { jp: "ろっかい", romaji: "rokkai", eng: "sixth floor", viet: "tầng 6" },
    { jp: "じゅっかい", romaji: "jukkai", eng: "tenth floor", viet: "tầng 10" },
    { jp: "なんかい", romaji: "nankai", eng: "which floor", viet: "tầng mấy" },
    { jp: "～や", romaji: "~ya", eng: "~ store", viet: "cửa hàng ~" },
    { jp: "いらっしゃいませ", romaji: "irasshaimase", eng: "welcome (to the store)", viet: "xin mời vào / chào mừng quý khách" },
    { jp: "これ", romaji: "kore", eng: "this (near me)", viet: "cái này" },
    { jp: "それ", romaji: "sore", eng: "that (near you)", viet: "cái đó" },
    { jp: "あれ", romaji: "are", eng: "that one over there", viet: "cái kia" },
    { jp: "この～", romaji: "kono~", eng: "this ~", viet: "cái ~ này" },
    { jp: "その～", romaji: "sono~", eng: "that ~", viet: "cái ~ đó" },
    { jp: "あの～", romaji: "ano~", eng: "that ~ over there", viet: "cái ~ kia" },
    { jp: "かばん", romaji: "kaban", eng: "bag", viet: "cặp / túi xách" },
    { jp: "ズボン", romaji: "zubon", eng: "trousers", viet: "quần dài" },
    { jp: "Tシャツ", romaji: "tiishatsu", eng: "t-shirt", viet: "áo thun" },
    { jp: "とけい", romaji: "tokei", eng: "watch / clock", viet: "đồng hồ" },
    { jp: "いくら", romaji: "ikura", eng: "how much", viet: "bao nhiêu tiền" },
    { jp: "じゃ", romaji: "ja", eng: "well then / bye", viet: "vậy thì / tạm biệt" },
    { jp: "ドル", romaji: "doru", eng: "dollar", viet: "đô la" },
    { jp: "ドン", romaji: "don", eng: "dong", viet: "đồng (tiền Việt Nam)" },
    { jp: "さかな", romaji: "sakana", eng: "fish", viet: "cá" },
    { jp: "にく", romaji: "niku", eng: "meat", viet: "thịt" },
    { jp: "ぎゅうにく", romaji: "gyuuniku", eng: "beef", viet: "thịt bò" },
    { jp: "ぶたにく", romaji: "butaniku", eng: "pork", viet: "thịt lợn" },
    { jp: "やさい", romaji: "yasai", eng: "vegetable", viet: "rau củ" },
    { jp: "いちご", romaji: "ichigo", eng: "strawberry", viet: "dâu tây" },
    { jp: "りんご", romaji: "ringo", eng: "apple", viet: "quả táo" },
    { jp: "りょうり", romaji: "ryouri", eng: "cooking / dish", viet: "món ăn / nấu ăn" },
    { jp: "カレー", romaji: "karee", eng: "curry", viet: "cà ri" },
    { jp: "スープ", romaji: "suupu", eng: "soup", viet: "súp / canh" },
    { jp: "とんかつ", romaji: "tonkatsu", eng: "pork cutlet", viet: "thịt lợn chiên xù" },
    { jp: "ハンバーグ", romaji: "hanbaagu", eng: "hamburger steak", viet: "bò băm viên / hamburger bò" },
    { jp: "ごはん", romaji: "gohan", eng: "rice / meal", viet: "cơm / bữa ăn" },
    { jp: "ライス", romaji: "raisu", eng: "rice (Western style)", viet: "cơm trắng (kiểu Tây)" },
    { jp: "ジュース", romaji: "juusu", eng: "juice / soft drink", viet: "nước ép / nước ngọt" },
    { jp: "コーヒー", romaji: "koohii", eng: "coffee", viet: "cà phê" },
    { jp: "こうちゃ", romaji: "koucha", eng: "black tea", viet: "hồng trà / trà đen" },
    { jp: "（お）ちゃ", romaji: "ocha", eng: "tea (green tea)", viet: "trà (trà xanh)" },
    { jp: "ビール", romaji: "biiru", eng: "beer", viet: "bia" },
    { jp: "ワイン", romaji: "wain", eng: "wine", viet: "rượu vang" },
    { jp: "インド", romaji: "indo", eng: "India", viet: "Ấn Độ" },
    { jp: "ドイツ", romaji: "doitsu", eng: "Germany", viet: "Đức" },
    { jp: "フランス", romaji: "furansu", eng: "France", viet: "Pháp" },
    { jp: "さいふ", romaji: "saifu", eng: "wallet", viet: "ví tiền" },
    { jp: "えいご", romaji: "eigo", eng: "English (language)", viet: "tiếng Anh" },
    { jp: "～つ", romaji: "~tsu", eng: "counter for general objects", viet: "bộ đếm đồ vật chung" },
    { jp: "とお", romaji: "too", eng: "ten (things)", viet: "mười cái" },
    { jp: "いくつ", romaji: "ikutsu", eng: "how many (things)", viet: "mấy cái / bao nhiêu cái" },
    { jp: "だれ", romaji: "dare", eng: "who", viet: "ai" },
    { jp: "ちゅうもんを おねがいします", romaji: "chuumon o onegaishimasu", eng: "I'd like to order, please", viet: "cho tôi gọi món ạ" },
    { jp: "どうぞ", romaji: "douzo", eng: "please / here you go", viet: "mời / đây ạ" }
  ],

  kanji: [
    { jp: "一",   hira: "いち",     romaji: "ichi",            eng: "one",                          viet: "một" },
    { jp: "一月", hira: "いちがつ", romaji: "ichigatsu",       eng: "January",                      viet: "tháng Một" },
    { jp: "一つ", hira: "ひとつ",   romaji: "hitotsu",         eng: "one (thing)",                  viet: "một cái / một thứ" },
    { jp: "二",   hira: "に",       romaji: "ni",    eng: "two",                          viet: "hai" },
    { jp: "二月", hira: "にがつ",   romaji: "nigatsu",         eng: "February",                     viet: "tháng Hai" },
    { jp: "二つ", hira: "ふたつ",   romaji: "futatsu",         eng: "two (things)",                 viet: "hai cái / hai thứ" },
    { jp: "三",   hira: "さん",     romaji: "san",     eng: "three",                        viet: "ba" },
    { jp: "三月", hira: "さんがつ", romaji: "sangatsu",        eng: "March",                        viet: "tháng Ba" },
    { jp: "三つ", hira: "みっつ",   romaji: "mittsu",          eng: "three (things)",               viet: "ba cái" },
    { jp: "四",   hira: "よん", romaji: "yon",       eng: "four",                         viet: "bốn" },
    { jp: "四月", hira: "しがつ",   romaji: "shigatsu",        eng: "April",                        viet: "tháng Tư" },
    { jp: "四つ", hira: "よっつ",   romaji: "yottsu",          eng: "four (things)",                viet: "bốn cái" },
    { jp: "五",   hira: "ご",       romaji: "go",    eng: "five",                         viet: "năm" },
    { jp: "五月", hira: "ごがつ",   romaji: "gogatsu",         eng: "May",                          viet: "tháng Năm" },
    { jp: "五つ", hira: "いつつ",   romaji: "itsutsu",         eng: "five (things)",                viet: "năm cái" },
    { jp: "六",   hira: "ろく",     romaji: "roku ",   eng: "six",                          viet: "sáu" },
    { jp: "六月", hira: "ろくがつ", romaji: "rokugatsu",       eng: "June",                         viet: "tháng Sáu" },
    { jp: "六つ", hira: "むっつ",   romaji: "muttsu",          eng: "six (things)",                 viet: "sáu cái" },
    { jp: "七",   hira: "しち",     romaji: "shichi", eng: "seven",                       viet: "bảy" },
    { jp: "七月", hira: "しちがつ", romaji: "shichigatsu",     eng: "July",                         viet: "tháng Bảy" },
    { jp: "七つ", hira: "ななつ",   romaji: "nanatsu",         eng: "seven (things)",               viet: "bảy cái" },
    { jp: "八",   hira: "はち",     romaji: "hachi",  eng: "eight",                        viet: "tám" },
    { jp: "八月", hira: "はちがつ", romaji: "hachigatsu",      eng: "August",                       viet: "tháng Tám" },
    { jp: "八つ", hira: "やっつ",   romaji: "yattsu",          eng: "eight (things)",               viet: "tám cái" },
    { jp: "九",   hira: "きゅう", romaji: "kyuu", eng: "nine",                   viet: "chín" },
    { jp: "九月", hira: "くがつ",   romaji: "kugatsu",         eng: "September",                    viet: "tháng Chín" },
    { jp: "九つ", hira: "ここのつ", romaji: "kokonotsu",       eng: "nine (things)",                viet: "chín cái" },
    { jp: "十",   hira: "じゅう", romaji: "juu",   eng: "ten",                          viet: "mười" },
    { jp: "十月", hira: "じゅうがつ", romaji: "juugatsu",     eng: "October",                      viet: "tháng Mười" },

    // Tiền tệ & số lớn
    { jp: "百",   hira: "ひゃく",   romaji: "hyaku",           eng: "hundred",                      viet: "trăm" },
    { jp: "千",   hira: "せん",     romaji: "sen",             eng: "thousand",                     viet: "nghìn" },
    { jp: "万",   hira: "まん",     romaji: "man",             eng: "ten thousand",                 viet: "vạn" },
    { jp: "円",   hira: "えん",     romaji: "en",              eng: "yen (currency)",               viet: "yên (đồng tiền)" },
    { jp: "百円", hira: "ひゃくえん", romaji: "hyakuen",       eng: "100 yen",                      viet: "100 yên" },
    { jp: "千円", hira: "せんえん", romaji: "sen'en",          eng: "1000 yen",                     viet: "1000 yên" },
    { jp: "一万円", hira: "いちまんえん", romaji: "ichiman'en", eng: "10,000 yen",                viet: "10.000 yên" },
    { jp: "百万", hira: "ひゃくまん", romaji: "hyakuman",      eng: "one million",                  viet: "một triệu" },
    { jp: "三百円", hira: "さんびゃくえん", romaji: "sanbyaku en", eng: "300 yen", viet: "300 yên" },
    { jp: "六百円", hira: "ろっぴゃくえん", romaji: "roppyaku en", eng: "600 yen", viet: "600 yên" },
    { jp: "八百円", hira: "はっぴゃくえん", romaji: "happyaku en", eng: "800 yen", viet: "800 yên" },
    { jp: "三千円", hira: "さんぜんえん", romaji: "sanzen en", eng: "3000 yen", viet: "3000 yên" },
    { jp: "八千円", hira: "はっせんえん", romaji: "hassen en", eng: "8000 yen", viet: "8000 yên" },
    
    { jp: "本", hira: "ほん", romaji: "hon", eng: "book", viet: "sách" },
    { jp: "水", hira: "みず", romaji: "mizu", eng: "water", viet: "nước" }

  ],

  grammar: [
    { 
      jp: "ここ／そこ／あそこ／どこ", 
      romaji: "koko / soko / asoko / doko", 
      eng: "Here / There / Over there / Where", 
      viet: "đây / đó / kia / đâu" 
    },
    { 
      jp: "こちら／そちら／あちら／どちら", 
      romaji: "kochira / sochira / achira / dochira", 
      eng: "This way / That way / Over that way / Which way (more polite)", 
      viet: "bên này / bên đó / bên kia / bên nào (lịch sự)" 
    },
    { 
      jp: "N を ください", 
      romaji: "N o kudasai", 
      eng: "Please give me N", 
      viet: "cho tôi N ạ / làm ơn đưa tôi N" 
    },
    { 
      jp: "いくらですか", 
      romaji: "ikura desu ka", 
      eng: "How much is it?", 
      viet: "bao nhiêu tiền vậy?" 
    },
    { 
      jp: "なんの N", 
      romaji: "nan no N", 
      eng: "What kind of N / What N", 
      viet: "N gì / loại N nào" 
    },
    { 
      jp: "どこの N", 
      romaji: "doko no N", 
      eng: "Which country's N / Where's N from", 
      viet: "N của nước nào / N ở đâu" 
    },
    { 
      jp: "だれの N", 
      romaji: "dare no N", 
      eng: "Whose N", 
      viet: "N của ai" 
    },
    { 
      jp: "「A」は～ごでなんですか。…「B」です。", 
      romaji: "“A” wa ~ go de nan desu ka? … “B” desu.", 
      eng: "How do you say 'A' in ~ language? … It’s 'B'.", 
      viet: "“A” trong tiếng ~ nói thế nào ạ? … Là “B” ạ." 
    }
  ]

};
