const lesson2 = {
  vocabularies: [
    { jp: "ここ", romaji: "koko", eng: "here" },
    { jp: "こちら", romaji: "kochira", eng: "this way" },
    { jp: "そこ", romaji: "soko", eng: "there" },
    { jp: "そちら", romaji: "sochira", eng: "that way" },
    { jp: "あそこ", romaji: "asoko", eng: "over there" },
    { jp: "あちら", romaji: "achira", eng: "that way over there" },
    { jp: "インフォメーション", romaji: "infomēshon", eng: "information desk" },
    { jp: "ＡＴＭ", romaji: "ATM", eng: "ATM" },
    { jp: "エスカレーター", romaji: "esukarētā", eng: "escalator" },
    { jp: "エレベーター", romaji: "erebētā", eng: "elevator" },
    { jp: "きつえんじょ", romaji: "kitsuenjo", eng: "smoking area" },
    { jp: "トイレ", romaji: "toire", eng: "toilet" },
    { jp: "レジ", romaji: "reji", eng: "cash register" },
    { jp: "きっさてん", romaji: "kissaten", eng: "coffee shop" },
    { jp: "スーパー", romaji: "sūpā", eng: "supermarket" },
    { jp: "１００円ショップ", romaji: "hyaku en shoppu", eng: "100 yen shop" },
    { jp: "レストラン", romaji: "resutoran", eng: "restaurant" },
    { jp: "ちか", romaji: "chika", eng: "basement" },
    { jp: "カメラ", romaji: "kamera", eng: "camera" },
    { jp: "けいたいでんわ", romaji: "keitai denwa", eng: "mobile phone" },
    { jp: "でんじしょ", romaji: "denshijo", eng: "electronic dictionary" },
    { jp: "パソコン", romaji: "pasokon", eng: "personal computer" },
    { jp: "くつ", romaji: "kutsu", eng: "shoes" },
    { jp: "けしゴム", romaji: "keshigomu", eng: "eraser" },
    { jp: "ペン", romaji: "pen", eng: "pen" },
    { jp: "トイレットペーパー", romaji: "toiretto pēpā", eng: "toilet paper" },
    { jp: "本", romaji: "hon", eng: "book" },
    { jp: "あぶら", romaji: "abura", eng: "oil" },
    { jp: "ケーキ", romaji: "kēki", eng: "cake" },
    { jp: "こめ", romaji: "kome", eng: "rice" },
    { jp: "たまご", romaji: "tamago", eng: "egg" },
    { jp: "パン", romaji: "pan", eng: "bread" },
    { jp: "水", romaji: "mizu", eng: "water" },
    { jp: "てんいん", romaji: "ten'in", eng: "salesperson" },
    { jp: "～かい", romaji: "~kai", eng: "floor" },
    { jp: "いっかい", romaji: "ikkai", eng: "first floor" },
    { jp: "ろっかい", romaji: "rokkai", eng: "sixth floor" },
    { jp: "じゅっかい", romaji: "jukkai", eng: "tenth floor" },
    { jp: "なんかい", romaji: "nankai", eng: "which floor" },
    { jp: "～や", romaji: "~ya", eng: "store" },
    { jp: "いらっしゃいませ", romaji: "irasshaimase", eng: "welcome" },
    { jp: "これ", romaji: "kore", eng: "this" },
    { jp: "それ", romaji: "sore", eng: "that" },
    { jp: "あれ", romaji: "are", eng: "that one over there" },
    { jp: "この～", romaji: "kono~", eng: "this ~" },
    { jp: "その～", romaji: "sono~", eng: "that ~" },
    { jp: "あの～", romaji: "ano~", eng: "that ~ over there" },
    { jp: "かばん", romaji: "kaban", eng: "bag" },
    { jp: "ズボン", romaji: "zubon", eng: "trousers" },
    { jp: "Tシャツ", romaji: "tiishatsu", eng: "t-shirt" },
    { jp: "とけい", romaji: "tokei", eng: "watch" },
    { jp: "～円", romaji: "~en", eng: "yen" },
    { jp: "百円", romaji: "hyaku en", eng: "100 yen" },
    { jp: "三百円", romaji: "sanbyaku en", eng: "300 yen" },
    { jp: "六百円", romaji: "roppyaku en", eng: "600 yen" },
    { jp: "八百円", romaji: "happyaku en", eng: "800 yen" },
    { jp: "千円", romaji: "sen en", eng: "1000 yen" },
    { jp: "三千円", romaji: "sanzen en", eng: "3000 yen" },
    { jp: "八千円", romaji: "hassen en", eng: "8000 yen" },
    { jp: "一万円", romaji: "ichiman en", eng: "10000 yen" },
    { jp: "いくら", romaji: "ikura", eng: "how much" },
    { jp: "じゃ", romaji: "ja", eng: "well then" },
    { jp: "ドル", romaji: "doru", eng: "dollar" },
    { jp: "ドン", romaji: "don", eng: "dong" },
    { jp: "さかな", romaji: "sakana", eng: "fish" },
    { jp: "にく", romaji: "niku", eng: "meat" },
    { jp: "ぎゅうにく", romaji: "gyuuniku", eng: "beef" },
    { jp: "ぶたにく", romaji: "butaniku", eng: "pork" },
    { jp: "やさい", romaji: "yasai", eng: "vegetable" },
    { jp: "いちご", romaji: "ichigo", eng: "strawberry" },
    { jp: "りんご", romaji: "ringo", eng: "apple" },
    { jp: "りょうり", romaji: "ryouri", eng: "cooking / dish" },
    { jp: "カレー", romaji: "karee", eng: "curry" },
    { jp: "スープ", romaji: "suupu", eng: "soup" },
    { jp: "とんかつ", romaji: "tonkatsu", eng: "pork cutlet" },
    { jp: "ハンバーグ", romaji: "hanbaagu", eng: "hamburger steak" },
    { jp: "ごはん", romaji: "gohan", eng: "rice / meal" },
    { jp: "ライス", romaji: "raisu", eng: "rice" },
    { jp: "ジュース", romaji: "juusu", eng: "juice / soft drink" },
    { jp: "コーヒー", romaji: "koohii", eng: "coffee" },
    { jp: "こうちゃ", romaji: "koucha", eng: "black tea" },
    { jp: "（お）ちゃ", romaji: "ocha", eng: "tea" },
    { jp: "ビール", romaji: "biiru", eng: "beer" },
    { jp: "ワイン", romaji: "wain", eng: "wine" },
    { jp: "インド", romaji: "indo", eng: "India" },
    { jp: "ドイツ", romaji: "doitsu", eng: "Germany" },
    { jp: "フランス", romaji: "furansu", eng: "France" },
    { jp: "さいふ", romaji: "saifu", eng: "wallet" },
    { jp: "えいご", romaji: "eigo", eng: "English (language)" },
    { jp: "～つ", romaji: "~tsu", eng: "counter for general objects" },
    { jp: "ひとつ", romaji: "hitotsu", eng: "one (thing)" },
    { jp: "ふたつ", romaji: "futatsu", eng: "two (things)" },
    { jp: "みっつ", romaji: "mittsu", eng: "three (things)" },
    { jp: "よっつ", romaji: "yottsu", eng: "four (things)" },
    { jp: "いつつ", romaji: "itsutsu", eng: "five (things)" },
    { jp: "むっつ", romaji: "muttsu", eng: "six (things)" },
    { jp: "ななつ", romaji: "nanatsu", eng: "seven (things)" },
    { jp: "やっつ", romaji: "yattsu", eng: "eight (things)" },
    { jp: "ここのつ", romaji: "kokonotsu", eng: "nine (things)" },
    { jp: "とお", romaji: "too", eng: "ten (things)" },
    { jp: "いくつ", romaji: "ikutsu", eng: "how many (things)" },
    { jp: "だれ", romaji: "dare", eng: "who" },
    { jp: "ちゅうもんを おねがいします", romaji: "chuumon o onegaishimasu", eng: "I'd like to order, please" },
    { jp: "どうぞ", romaji: "douzo", eng: "please / here you go" }
  ],

  kanji: [
    { jp: "一", romaji: "ichi", eng: "one" },
    { jp: "二", romaji: "ni", eng: "two" },
    { jp: "三", romaji: "san", eng: "three" },
    { jp: "四", romaji: "yon", eng: "four" },
    { jp: "五", romaji: "go", eng: "five" },
    { jp: "六", romaji: "roku", eng: "six" },
    { jp: "七", romaji: "nana", eng: "seven" },
    { jp: "八", romaji: "hachi", eng: "eight" },
    { jp: "九", romaji: "kyuu", eng: "nine" },
    { jp: "十", romaji: "juu", eng: "ten" },
    { jp: "百", romaji: "hyaku", eng: "hundred" },
    { jp: "千", romaji: "sen", eng: "thousand" },
    { jp: "万", romaji: "man", eng: "ten thousand" },
    { jp: "円", romaji: "en", eng: "yen" }
  ],

  grammar: [
    { 
      jp: "ここ／そこ／あそこ／どこ", 
      romaji: "koko / soko / asoko / doko", 
      eng: "Here / There / Over there / Where"
    },
    { 
      jp: "こちら／そちら／あちら／どちら", 
      romaji: "kochira / sochira / achira / dochira", 
      eng: "This way / That way / Over that way / Which way (more polite)"
    },
    { 
      jp: "N を ください", 
      romaji: "N o kudasai", 
      eng: "Please give me N"
    },
    { 
      jp: "いくらですか", 
      romaji: "ikura desu ka", 
      eng: "How much is it?"
    },
    { 
      jp: "なんの N", 
      romaji: "nan no N", 
      eng: "What kind of N / What N"
    },
    { 
      jp: "どこの N", 
      romaji: "doko no N", 
      eng: "Which country's N / Where's N from"
    },
    { 
      jp: "だれの N", 
      romaji: "dare no N", 
      eng: "Whose N"
    },
    { 
      jp: "「A」は～ごでなんですか。…「B」です。", 
      romaji: "“A” wa ~ go de nan desu ka? … “B” desu.", 
      eng: "How do you say 'A' in ~ language? … It’s 'B'."
    }
  ]

};
