const lesson1 = {
  vocabularies: [
    { jp: "私", romaji: "watashi", eng: "I" },
    { jp: "なまえ", romaji: "namae", eng: "name" },
    { jp: "くに", romaji: "kuni", eng: "country" },
    { jp: "日本", romaji: "nihon", eng: "Japan" },
    { jp: "かんこく", romaji: "kankoku", eng: "Korea" },
    { jp: "ちゅうごく", romaji: "chuugoku", eng: "China" },
    { jp: "アメリカ", romaji: "amerika", eng: "America" },
    { jp: "イタリア", romaji: "itaria", eng: "Italy" },
    { jp: "オーストラリア", romaji: "oosutoraria", eng: "Australia" },
    { jp: "ロシア", romaji: "roshia", eng: "Russia" },
    { jp: "タイ", romaji: "tai", eng: "Thailand" },
    { jp: "高校", romaji: "koukou", eng: "high school" },
    { jp: "大学", romaji: "daigaku", eng: "university" },
    { jp: "日本語学校", romaji: "nihongo gakkou", eng: "Japanese language school" },
    { jp: "しごと", romaji: "shigoto", eng: "job" },
    { jp: "学生", romaji: "gakusei", eng: "student" },
    { jp: "先生", romaji: "sensei", eng: "instructor" },
    { jp: "きょうし", romaji: "kyoushi", eng: "teacher" },
    { jp: "かいしゃいん", romaji: "kaishain", eng: "company employee" },
    { jp: "〜しゃいん", romaji: "~shain", eng: "employee of ~ company" },
    { jp: "〜さん", romaji: "~san", eng: "Mr. / Ms. / Mrs." },
    { jp: "〜人", romaji: "~jin", eng: "person / nationality" },
    { jp: "どちら", romaji: "dochira", eng: "where / which way" },
    { jp: "はじめまして", romaji: "hajimemashite", eng: "Nice to meet you (first time)" },
    { jp: "よろしくおねがいします", romaji: "yoroshiku onegaishimasu", eng: "Please take care of me / I look forward to working with you" },
    { jp: "こちらこそ", romaji: "kochirakoso", eng: "Likewise / same here" },
    { jp: "あのう", romaji: "anou", eng: "um... / excuse me..." },
    { jp: "すみません", romaji: "sumimasen", eng: "excuse me / I'm sorry" },
    { jp: "そうですか", romaji: "sou desu ka", eng: "Is that so? / I see" },
    { jp: "誕生日", romaji: "tanjoubi", eng: "birthday" },
    { jp: "ブラジル", romaji: "burajiru", eng: "Brazil" },
    { jp: "いつ", romaji: "itsu", eng: "when" },
    { jp: "一月", romaji: "ichigatsu", eng: "January" },
    { jp: "二月", romaji: "nigatsu", eng: "February" },
    { jp: "三月", romaji: "sangatsu", eng: "March" },
    { jp: "四月", romaji: "shigatsu", eng: "April" },
    { jp: "五月", romaji: "gogatsu", eng: "May" },
    { jp: "六月", romaji: "rokugatsu", eng: "June" },
    { jp: "七月", romaji: "shichigatsu", eng: "July" },
    { jp: "八月", romaji: "hachigatsu", eng: "August" },
    { jp: "九月", romaji: "kugatsu", eng: "September" },
    { jp: "十月", romaji: "juugatsu", eng: "October" },
    { jp: "十一月", romaji: "juuichigatsu", eng: "November" },
    { jp: "十二月", romaji: "juunigatsu", eng: "December" },
    { jp: "一日", romaji: "tsuitachi", eng: "1st day" },
    { jp: "二日", romaji: "futsuka", eng: "2nd day" },
    { jp: "三日", romaji: "mikka", eng: "3rd day" },
    { jp: "四日", romaji: "yokka", eng: "4th day" },
    { jp: "五日", romaji: "itsuka", eng: "5th day" },
    { jp: "六日", romaji: "muika", eng: "6th day" },
    { jp: "七日", romaji: "nanoka", eng: "7th day" },
    { jp: "八日", romaji: "youka", eng: "8th day" },
    { jp: "九日", romaji: "kokonoka", eng: "9th day" },
    { jp: "十日", romaji: "tooka", eng: "10th day" },
    { jp: "十一日", romaji: "juuichinichi", eng: "11th day" },
    { jp: "十二日", romaji: "juuninichi", eng: "12th day" },
    { jp: "十三日", romaji: "juusannichi", eng: "13th day" },
    { jp: "十四日", romaji: "juuyokka", eng: "14th day" },
    { jp: "十五日", romaji: "juugonichi", eng: "15th day" },
    { jp: "十六日", romaji: "juurokunichi", eng: "16th day" },
    { jp: "十七日", romaji: "juushichinichi", eng: "17th day" },
    { jp: "十八日", romaji: "juuhachinichi", eng: "18th day" },
    { jp: "十九日", romaji: "juukunichi", eng: "19th day" },
    { jp: "二十日", romaji: "hatsuka", eng: "20th day" },
    { jp: "二十一日", romaji: "nijuuichinichi", eng: "21st day" },
    { jp: "二十二日", romaji: "nijuuninichi", eng: "22nd day" },
    { jp: "二十三日", romaji: "nijuusannichi", eng: "23rd day" },
    { jp: "二十四日", romaji: "nijuuyokka", eng: "24th day" },
    { jp: "二十五日", romaji: "nijuugonichi", eng: "25th day" },
    { jp: "二十六日", romaji: "nijuurokunichi", eng: "26th day" },
    { jp: "二十七日", romaji: "nijuushichinichi", eng: "27th day" },
    { jp: "二十八日", romaji: "nijuuhachinichi", eng: "28th day" },
    { jp: "二十九日", romaji: "nijuukunichi", eng: "29th day" },
    { jp: "三十日", romaji: "sanjuunichi", eng: "30th day" },
    { jp: "三十一日", romaji: "sanjuuichinichi", eng: "31st day" },
    { jp: "一才", romaji: "issai", eng: "1 year old" },
    { jp: "二才", romaji: "nisai", eng: "2 years old" },
    { jp: "三才", romaji: "sansai", eng: "3 years old" },
    { jp: "四才", romaji: "yonsai", eng: "4 years old" },
    { jp: "五才", romaji: "gosai", eng: "5 years old" },
    { jp: "六才", romaji: "rokusai", eng: "6 years old" },
    { jp: "七才", romaji: "nanasai", eng: "7 years old" },
    { jp: "八才", romaji: "hassai", eng: "8 years old" },
    { jp: "九才", romaji: "kyuusai", eng: "9 years old" },
    { jp: "十才", romaji: "jussai", eng: "10 years old" },
    { jp: "十一才", romaji: "juuissai", eng: "11 years old" },
    { jp: "十八才", romaji: "juuhassai", eng: "18 years old" },
    { jp: "二十才", romaji: "hatachi", eng: "20 years old" },
    { jp: "三十才", romaji: "sanjuussai", eng: "30 years old" },
    { jp: "何才", romaji: "nansai", eng: "how old" },
    { jp: "しゅみ", romaji: "shumi", eng: "hobby" },
    { jp: "スポーツ", romaji: "supōtsu", eng: "sports" },
    { jp: "サッカー", romaji: "sakkā", eng: "soccer" },
    { jp: "テニス", romaji: "tenisu", eng: "tennis" },
    { jp: "すいえい", romaji: "suiei", eng: "swimming" },
    { jp: "えいが", romaji: "eiga", eng: "movie" },
    { jp: "おんがく", romaji: "ongaku", eng: "music" },
    { jp: "どくしょ", romaji: "dokusho", eng: "reading" },
    { jp: "りょこう", romaji: "ryokō", eng: "travel" },
    { jp: "りょうり", romaji: "ryōri", eng: "cooking / food" },
    { jp: "何", romaji: "nani", eng: "what" },
    { jp: "あ（っ）", romaji: "a (tsu)", eng: "ah! / oh!" },
    { jp: "わあ", romaji: "waa", eng: "wow" },
    { jp: "おなじですね", romaji: "onaji desu ne", eng: "same, isn’t it?" }
  ],
    kanji: [
    { jp: "私", romaji: "watashi", eng: "I / me" },
    { jp: "人", romaji: "hito / nin / jin", eng: "person / people" },
    { jp: "才", romaji: "sai", eng: "years old (age counter)" },
    { jp: "学", romaji: "gaku / manabu", eng: "study / learning" },
    { jp: "生", romaji: "sei / shou / ikiru", eng: "life / birth / student" },
    { jp: "校", romaji: "kou", eng: "school" },
    { jp: "日", romaji: "hi / nichi / jitsu", eng: "day / sun / Japan" },
    { jp: "本", romaji: "hon / moto", eng: "book / origin / Japan" },
    { jp: "語", romaji: "go / kata(ru)", eng: "language / word / speak" }
    ],
    grammar: [
    { 
        jp: "N1はN2です", 
        romaji: "N1 wa N2 desu", 
        eng: "N1 is N2"
    },
    { 
        jp: "N1は〜のN2です", 
        romaji: "N1 wa ~ no N2 desu", 
        eng: "N1 is the N2 of ~"
    },
    { 
        jp: "N1のN2です", 
        romaji: "N1 no N2 desu", 
        eng: "N2 of N1 / N2 belonging to N1"
    },
    { 
        jp: "N1もN2です", 
        romaji: "N1 mo N2 desu", 
        eng: "N1 is also N2"
    },
    { 
        jp: "N1はN2じゃありません（ではありません）", 
        romaji: "N1 wa N2 ja arimasen (dewa arimasen)", 
        eng: "N1 is not N2"
    },
    { 
        jp: "N1とN2", 
        romaji: "N1 to N2", 
        eng: "N1 and N2"
    },
    { 
        jp: "Nはどこですか", 
        romaji: "N wa doko desu ka", 
        eng: "Where is N?"
    },
    { 
        jp: "Nは？", 
        romaji: "N wa?", 
        eng: "How about N? / And N?"
    },
    { 
        jp: "N1はN2ですか", 
        romaji: "N1 wa N2 desu ka", 
        eng: "Is N1 N2?"
    }
    ]

};
