const lesson3 = {
  vocabularies: [
    { jp: "いま", romaji: "ima", eng: "now" },
    { jp: "ごぜん", romaji: "gozen", eng: "morning / AM" },
    { jp: "ごご", romaji: "gogo", eng: "afternoon / PM" },
    { jp: "ひる", romaji: "hiru", eng: "noon" },
    { jp: "ぎんこう", romaji: "ginkou", eng: "bank" },
    { jp: "たいいくかん", romaji: "taiikukan", eng: "gymnasium" },
    { jp: "としょかん", romaji: "toshokan", eng: "library" },
    { jp: "びょういん", romaji: "byouin", eng: "hospital" },
    { jp: "ゆうびんきょく", romaji: "yuubinkyoku", eng: "post office" },
    { jp: "じゅぎょう", romaji: "jugyou", eng: "class / lesson" },
    { jp: "テスト", romaji: "tesuto", eng: "test / exam" },
    { jp: "やすみ", romaji: "yasumi", eng: "rest / holiday" },
    { jp: "時間", romaji: "jikan", eng: "time" },
    { jp: "一分", romaji: "ippun", eng: "1 minute" },
    { jp: "二分", romaji: "nifun", eng: "2 minutes" },
    { jp: "三分", romaji: "sanpun", eng: "3 minutes" },
    { jp: "四分", romaji: "yonpun", eng: "4 minutes" },
    { jp: "五分", romaji: "gofun", eng: "5 minutes" },
    { jp: "六分", romaji: "roppun", eng: "6 minutes" },
    { jp: "七分", romaji: "nanafun", eng: "7 minutes" },
    { jp: "八分", romaji: "happun", eng: "8 minutes" },
    { jp: "九分", romaji: "kyuufun", eng: "9 minutes" },
    { jp: "十分", romaji: "juppun", eng: "10 minutes" },
    { jp: "十五分", romaji: "juugofun", eng: "15 minutes" },
    { jp: "二十分", romaji: "nijuppun", eng: "20 minutes" },
    { jp: "三十分", romaji: "sanjuppun", eng: "30 minutes" },
    { jp: "何分", romaji: "nanpun", eng: "how many minutes" },
    { jp: "～時半", romaji: "~jihan", eng: "half past ~" },
    { jp: "～曜日", romaji: "~youbi", eng: "day of the week ~" },
    { jp: "月曜日", romaji: "getsuyoubi", eng: "Monday" },
    { jp: "火曜日", romaji: "kayoubi", eng: "Tuesday" },
    { jp: "水曜日", romaji: "suiyoubi", eng: "Wednesday" },
    { jp: "木曜日", romaji: "mokuyoubi", eng: "Thursday" },
    { jp: "金曜日", romaji: "kinyoubi", eng: "Friday" },
    { jp: "土曜日", romaji: "doyoubi", eng: "Saturday" },
    { jp: "日曜日", romaji: "nichiyoubi", eng: "Sunday" },
    { jp: "何曜日", romaji: "nanyoubi", eng: "what day" },
    { jp: "スケジュール", romaji: "sukejuuru", eng: "schedule / plan" },
    { jp: "アルバイト", romaji: "arubaito", eng: "part-time job" },
    { jp: "スキー", romaji: "sukii", eng: "skiing" },
    { jp: "パーティー", romaji: "paatii", eng: "party" },
    { jp: "バーベキュー", romaji: "baabekyuu", eng: "barbecue" },
    { jp: "はな火", romaji: "hanabi", eng: "fireworks" },
    { jp: "(お)はなみ", romaji: "ohanami", eng: "cherry blossom viewing" },
    { jp: "ホームステイ", romaji: "hoomusutei", eng: "homestay" },
    { jp: "(お)まつり", romaji: "omatsuri", eng: "festival" },
    { jp: "うみ", romaji: "umi", eng: "sea / beach" },
    { jp: "こうえん", romaji: "kouen", eng: "park" },
    { jp: "さくら", romaji: "sakura", eng: "cherry blossom" },
    { jp: "(お)さけ", romaji: "osake", eng: "Japanese rice wine (sake)" },
    { jp: "(お)すし", romaji: "osushi", eng: "sushi" },
    { jp: "バス", romaji: "basu", eng: "bus" },
    { jp: "(お)べんとう", romaji: "obentou", eng: "boxed lunch" },
    { jp: "１年", romaji: "ichinen", eng: "one year" },
    { jp: "はる", romaji: "haru", eng: "spring" },
    { jp: "なつ", romaji: "natsu", eng: "summer" },
    { jp: "あき", romaji: "aki", eng: "autumn" },
    { jp: "ふゆ", romaji: "fuyu", eng: "winter" },
    { jp: "ゴールデンウィーク", romaji: "goorudenwiiku", eng: "Golden Week" },
    { jp: "何", romaji: "nani", eng: "what" },
    { jp: "いきます", romaji: "ikimasu", eng: "to go" },
    { jp: "かえります", romaji: "kaerimasu", eng: "to return / go home" },
    { jp: "のみます", romaji: "nomimasu", eng: "to drink" },
    { jp: "たべます", romaji: "tabemasu", eng: "to eat" },
    { jp: "みます", romaji: "mimasu", eng: "to see / to watch" },
    { jp: "します", romaji: "shimasu", eng: "to do / to play / to hold" },
    { jp: "スキーをします", romaji: "sukii o shimasu", eng: "to ski" },
    { jp: "いいですね", romaji: "ii desu ne", eng: "that sounds good / nice!" },
    { jp: "えっ", romaji: "e", eng: "eh? / huh?" },
    { jp: "へえ", romaji: "hee", eng: "wow / really" },
    { jp: "あさ", romaji: "asa", eng: "morning" },
    { jp: "よる", romaji: "yoru", eng: "evening / night" },
    { jp: "まいにち", romaji: "mainichi", eng: "every day" },
    { jp: "まいあさ", romaji: "maiasa", eng: "every morning" },
    { jp: "まいばん", romaji: "maiban", eng: "every evening" },
    { jp: "あさごはん", romaji: "asagohan", eng: "breakfast" },
    { jp: "ひるごはん", romaji: "hirugohan", eng: "lunch" },
    { jp: "うち", romaji: "uchi", eng: "home, house" },
    { jp: "かいしゃ", romaji: "kaisha", eng: "company" },
    { jp: "学校", romaji: "gakkou", eng: "school" },
    { jp: "コンビニ", romaji: "konbini", eng: "convenience store" },
    { jp: "ぎゅうにゅう", romaji: "gyuunyuu", eng: "milk" },
    { jp: "くだもの", romaji: "kudamono", eng: "fruit" },
    { jp: "サラダ", romaji: "sarada", eng: "salad" },
    { jp: "チーズ", romaji: "chiizu", eng: "cheese" },
    { jp: "インターネット", romaji: "intaanetto", eng: "internet" },
    { jp: "しんぶん", romaji: "shinbun", eng: "newspaper" },
    { jp: "テレビ", romaji: "terebi", eng: "television" },
    { jp: "シーディー、ディーブイディー", romaji: "shiidii, diibuidii", eng: "CD, DVD" },
    { jp: "何も", romaji: "nanimo", eng: "anything" },
    { jp: "どこ（へ）も", romaji: "doko(e)mo", eng: "anywhere" },
    { jp: "かいます", romaji: "kaimasu", eng: "buy" },
    { jp: "ききます", romaji: "kikimasu", eng: "listen" },
    { jp: "はたらきます", romaji: "hatarakimasu", eng: "work" },
    { jp: "よみます", romaji: "yomimasu", eng: "read" },
    { jp: "ねます", romaji: "nemasu", eng: "sleep" },
    { jp: "べんきょうします", romaji: "benkyoushimasu", eng: "study" },
    { jp: "きます", romaji: "kimasu", eng: "come, arrive" }
  ],

  kanji: [
    { jp: "月", romaji: "tsuki", eng: "moon / month" },
    { jp: "火", romaji: "hi", eng: "fire" },
    { jp: "水", romaji: "mizu", eng: "water" },
    { jp: "木", romaji: "ki", eng: "tree / wood" },
    { jp: "金", romaji: "kin", eng: "gold / money" },
    { jp: "土", romaji: "tsuchi", eng: "earth / soil" },
    { jp: "曜", romaji: "yō", eng: "day(of the week)" },
    { jp: "何", romaji: "nani", eng: "what" },
    { jp: "年", romaji: "nen", eng: "year" },
    { jp: "時", romaji: "ji", eng: "time / hour" },
    { jp: "間", romaji: "kan", eng: "interval / between" },
    { jp: "分", romaji: "fun", eng: "minute / divide" }
  ],
  grammar: [
  { 
    jp: "Vます／Vません", 
    romaji: "V masu / V masen", 
    eng: "Will do / Will not do"
  },
  { 
    jp: "N（場所）へいきます／きます／かえります", 
    romaji: "N (basho) e ikimasu / kimasu / kaerimasu", 
    eng: "Go / come / return to a place N"
  },
  { 
    jp: "N（を）Vます", 
    romaji: "N (o) V masu", 
    eng: "Perform an action V on object N"
  },
  { 
    jp: "N（時間）にVます", 
    romaji: "N (jikan) ni V masu", 
    eng: "Do V at time N"
  },
  { 
    jp: "N（場所）でVます", 
    romaji: "N (basho) de V masu", 
    eng: "Do V at/in place N"
  },
  { 
    jp: "N（時間／曜日）からN（時間／曜日）まで", 
    romaji: "N (jikan / youbi) kara N (jikan / youbi) made", 
    eng: "From N (time/day) to N (time/day)"
  },
  { 
    jp: "N1やN2など", 
    romaji: "N1 ya N2 nado", 
    eng: "N1, N2, etc."
  },
  { 
    jp: "何もしません／どこ（へ）もいきません", 
    romaji: "nani mo shimasen / doko (e) mo ikimasen", 
    eng: "Do nothing / Go nowhere"
  }
  ]
};
